"""Tests for N-camera floor-marker calibration and its residual gate.

Marker data is generated by projecting known floor points through posed
`VirtualCamera`s, so the geometry is exact and a deliberate mismarking is the
only source of error. That is what lets a test assert the gate FAILS — which is
the property that matters, because a gate that cannot fail is decoration.
"""

from __future__ import annotations

import numpy as np
import pytest
import yaml

from mcreid.calib.floor import (
    MAX_CROSS_CAMERA_DISAGREEMENT_M,
    MAX_HELDOUT_ERROR_M,
    MIN_MARKERS,
    FloorMarkers,
    build_and_gate,
    load_floor_markers,
    measure_agreement,
    rig_from_floor_markers,
)
from mcreid.calib.geometry import image_to_ground
from mcreid.sim.virtual_camera import VirtualCamera

CAM0 = VirtualCamera(
    camera_id="cam0", position_m=(0.4, 0.4, 2.6), yaw_deg=45.0, pitch_deg=28.0,
    hfov_deg=90.0, image_size=(1280, 720),
)
CAM1 = VirtualCamera(
    camera_id="cam1", position_m=(5.6, 4.6, 2.6), yaw_deg=225.0, pitch_deg=28.0,
    hfov_deg=90.0, image_size=(640, 480),
)
CAMERAS = {"cam0": CAM0, "cam1": CAM1}

# Eight markers spread over a 6x5 m floor. Deliberately not co-linear and not a
# neat rectangle: a degenerate layout fits any homography and hides everything.
WORLD = np.array(
    [
        [1.0, 1.0], [5.0, 1.0], [5.0, 4.0], [1.0, 4.0],
        [3.0, 2.5], [2.0, 3.5], [4.5, 2.0], [3.5, 1.2],
    ],
    dtype=np.float64,
)


def _markers(world: np.ndarray = WORLD, jitter_px: float = 0.0, seed: int = 0) -> FloorMarkers:
    rng = np.random.default_rng(seed)
    image_points = {}
    for camera_id, camera in CAMERAS.items():
        pts, ok = camera.project(np.hstack([world, np.zeros((world.shape[0], 1))]))
        assert ok.all(), "fixture markers must be visible to every camera"
        if jitter_px:
            pts = pts + rng.normal(0.0, jitter_px, size=pts.shape)
        image_points[camera_id] = pts
    return FloorMarkers(
        world_points=world,
        image_points=image_points,
        image_sizes={cid: cam.image_size for cid, cam in CAMERAS.items()},
    )


# --- the gate must be able to fail ---------------------------------------------------------------


def test_four_markers_are_refused_because_the_gate_would_be_an_identity():
    """Four correspondences fit EXACTLY, so a residual computed on them is ~1e-15
    and the cross-camera agreement is an algebraic identity, not a measurement.
    A four-point rig is not un-gateable by accident; it is un-gateable in
    principle."""
    with pytest.raises(ValueError, match="at least 6 floor markers"):
        _markers(world=WORLD[:4])
    assert MIN_MARKERS == 6


def test_a_clean_rig_passes():
    agreement = measure_agreement(_markers())
    assert agreement.passes
    assert agreement.max_disagreement_m < 1e-6
    for camera in agreement.per_camera:
        assert camera.max_error_m < 1e-6


def test_one_mismarked_point_fails_the_gate():
    """The property the whole module exists for. A marker clicked 60 px off in
    one camera must be refused, not averaged away."""
    markers = _markers()
    corrupted = {cid: pts.copy() for cid, pts in markers.image_points.items()}
    corrupted["cam0"][2] += np.array([60.0, 45.0])
    broken = FloorMarkers(
        world_points=markers.world_points,
        image_points=corrupted,
        image_sizes=markers.image_sizes,
    )
    agreement = measure_agreement(broken)
    assert not agreement.passes
    assert agreement.worst_pair == ("cam0", "cam1")
    with pytest.raises(ValueError, match="REFUSED"):
        build_and_gate(broken)


def test_the_gate_names_which_camera_and_which_marker():
    """A refusal that does not say where to re-measure costs another session."""
    markers = _markers()
    corrupted = {cid: pts.copy() for cid, pts in markers.image_points.items()}
    corrupted["cam1"][5] += np.array([80.0, 80.0])
    agreement = measure_agreement(
        FloorMarkers(markers.world_points, corrupted, markers.image_sizes)
    )
    assert agreement.worst_marker == 5
    report = "\n".join(agreement.report())
    assert "FAIL" in report and "cam1" in report and "marker 5" in report


def test_leave_one_out_is_not_vacuous():
    """With an exact fit the in-sample residual is ~1e-15 for ANY rig, including
    a mismarked one. The held-out error is what separates them."""
    markers = _markers()
    corrupted = {cid: pts.copy() for cid, pts in markers.image_points.items()}
    corrupted["cam0"][1] += np.array([50.0, 40.0])
    broken = measure_agreement(
        FloorMarkers(markers.world_points, corrupted, markers.image_sizes)
    )
    clean = measure_agreement(markers)
    cam0_broken = next(c for c in broken.per_camera if c.camera_id == "cam0")
    cam0_clean = next(c for c in clean.per_camera if c.camera_id == "cam0")
    assert cam0_broken.max_error_m > 100 * max(cam0_clean.max_error_m, 1e-9)


@pytest.mark.parametrize("jitter_px", [0.25, 0.5])
def test_sub_pixel_marking_passes(jitter_px: float):
    """Points clicked by hand are not exact. Measured pass rate over 12 seeds:
    0.25 px 100 %, 0.5 px 100 %, 1.0 px 75 %, 1.5 px 50 %, 2.0 px 8 %, 3.0 px 0 %."""
    agreement = measure_agreement(_markers(jitter_px=jitter_px, seed=3))
    assert agreement.passes, "\n".join(agreement.report())


def test_two_pixels_of_marking_error_is_already_too_much_on_the_vga_camera():
    """THE CONSTRAINT THE CAPTURE PROCEDURE HAS TO CARRY, and it is not obvious.

    2 px of click error puts cam1 at 0.40 m held-out error and the pair at
    0.61 m of disagreement — refused. cam0 at the same jitter is 0.13 m and
    fine. The difference is resolution: cam1 is 640x480 looking across a 6 m
    room, so one pixel subtends several centimetres of floor and its error is
    ~3x cam0's. Markers must be clicked on a ZOOMED view, and the
    lowest-resolution camera is the one that decides whether the rig passes.
    """
    agreement = measure_agreement(_markers(jitter_px=2.0, seed=3))
    assert not agreement.passes
    cam0 = next(c for c in agreement.per_camera if c.camera_id == "cam0")
    cam1 = next(c for c in agreement.per_camera if c.camera_id == "cam1")
    assert cam1.max_error_m > 2.0 * cam0.max_error_m


def test_more_markers_buy_back_marking_accuracy():
    """Why the procedure asks for 12 and not the 6 minimum. At a fixed 1.5 px of
    jitter, measured pass rate over 12 seeds: 6 markers 0 %, 8 markers 50 %,
    10 markers 58 %, 12 markers 92 %. Least squares over more correspondences
    averages the click error down, and asking for six more points is far cheaper
    than asking for a steadier hand."""
    dense = np.vstack([WORLD, [[2.5, 1.8], [4.0, 3.2], [1.5, 2.8], [4.8, 4.2]]])
    sparse_failures = sum(
        not measure_agreement(_markers(world=WORLD[:6], jitter_px=1.5, seed=s)).passes
        for s in range(8)
    )
    dense_passes = sum(
        measure_agreement(_markers(world=dense, jitter_px=1.5, seed=s)).passes
        for s in range(8)
    )
    assert sparse_failures >= 7, "six markers should mostly fail at this jitter"
    assert dense_passes >= 6, "twelve markers should mostly pass at this jitter"


def test_gross_jitter_is_refused():
    agreement = measure_agreement(_markers(jitter_px=25.0, seed=5))
    assert not agreement.passes


# --- the rig the gate produces ----------------------------------------------------------------


def test_both_cameras_land_on_the_same_world_point():
    """The whole mechanism: a shared world list is what makes '1.2 m from the
    door' mean the same thing to both cameras."""
    markers = _markers()
    rig = rig_from_floor_markers(markers)
    for index, expected in enumerate(markers.world_points):
        estimates = []
        for camera_id in markers.camera_ids:
            pixel = markers.image_points[camera_id][index : index + 1]
            world, ok = image_to_ground(rig.get(camera_id), pixel)
            assert ok.all()
            estimates.append(world[0])
        for estimate in estimates:
            np.testing.assert_allclose(estimate, expected, atol=1e-6)
        assert float(np.linalg.norm(estimates[0] - estimates[1])) < 1e-6


def test_the_rig_records_that_no_lens_model_was_estimated():
    """A floor-marker calibration has no information about distortion, and
    inventing coefficients would move the very pixels that were measured."""
    rig = rig_from_floor_markers(_markers())
    for camera in rig.cameras:
        assert not camera.undistort_maps_needed()
        assert "no lens model" in camera.notes
    assert "comparable between cameras" in rig.world_notes


def test_the_rig_declares_a_floor_extent_so_the_bev_can_be_sized():
    rig = rig_from_floor_markers(_markers())
    x0, y0, x1, y1 = rig.floor_extent()
    assert x1 - x0 > 4.0 and y1 - y0 > 3.0


def test_build_and_gate_returns_both_the_rig_and_the_evidence():
    rig, agreement = build_and_gate(_markers())
    assert rig.camera_ids == ["cam0", "cam1"]
    assert agreement.passes
    assert agreement.overlap_m2 > 5.0


# --- the bounds are tied to the fusion stage, not invented ------------------------------------


def test_the_bounds_sit_below_the_gates_they_have_to_survive():
    from mcreid.fusion.global_id import FusionConfig

    config = FusionConfig()
    assert config.merge_radius_m > MAX_HELDOUT_ERROR_M
    assert config.merge_radius_m > MAX_CROSS_CAMERA_DISAGREEMENT_M
    assert MAX_HELDOUT_ERROR_M < MAX_CROSS_CAMERA_DISAGREEMENT_M
    # The cross-camera ceiling IS the birth-clustering radius: two cameras that
    # disagree by more than the distance at which the fusion stage stops
    # believing they see one person are not in a shared frame in any useful way.
    assert pytest.approx(0.35) == MAX_CROSS_CAMERA_DISAGREEMENT_M


# --- the YAML the user actually writes --------------------------------------------------------


def test_the_marker_file_round_trips(tmp_path):
    markers = _markers()
    path = tmp_path / "floor.yaml"
    path.write_text(
        yaml.safe_dump(
            {
                "world_points": markers.world_points.tolist(),
                "cameras": {
                    cid: {
                        "image_size": list(markers.image_sizes[cid]),
                        "image_points": markers.image_points[cid].tolist(),
                    }
                    for cid in markers.camera_ids
                },
            }
        ),
        encoding="utf-8",
    )
    loaded = load_floor_markers(path)
    assert loaded.camera_ids == ["cam0", "cam1"]
    assert loaded.n_markers == markers.n_markers
    np.testing.assert_allclose(loaded.world_points, markers.world_points)
    assert measure_agreement(loaded).passes


def test_a_camera_with_the_wrong_number_of_points_is_refused():
    markers = _markers()
    short = {cid: pts.copy() for cid, pts in markers.image_points.items()}
    short["cam1"] = short["cam1"][:-1]
    with pytest.raises(ValueError, match="cam1: expected 8 image points"):
        FloorMarkers(markers.world_points, short, markers.image_sizes)


def test_a_camera_with_no_declared_size_is_refused():
    markers = _markers()
    with pytest.raises(ValueError, match="no image_size"):
        FloorMarkers(markers.world_points, markers.image_points, {"cam0": (1280, 720)})


def test_a_missing_file_says_so(tmp_path):
    with pytest.raises(FileNotFoundError, match="floor marker file not found"):
        load_floor_markers(tmp_path / "nope.yaml")


def test_a_file_missing_world_points_says_which_key(tmp_path):
    path = tmp_path / "floor.yaml"
    path.write_text(yaml.safe_dump({"cameras": {}}), encoding="utf-8")
    with pytest.raises(ValueError, match="missing required key 'world_points'"):
        load_floor_markers(path)
